// Copyright © 2025 Brad Howes. All rights reserved.

import Foundation
import Engine

/**
 Collection of unique tags for each SF2 file in the bundle
 */
public enum SF2ResourceFileTag: Int, CaseIterable, Sendable {

  // NOTE: values must be 1-based in order to match the SQL autogenerated primary key SoundFont.IDs
  case fluidFont = 1
  case freeFont = 2
  case museScore = 3
  case rolandNicePiano = 4

  public var id: SoundFont.ID { .init(rawValue: Int64(self.rawValue)) }
}

extension SF2ResourceFileTag {

  public static let fluidFontFileName = "FluidR3_GM"
  public static let freeFontFileName = "FreeFont"
  public static let museScoreFileName = "GeneralUser GS MuseScore v1.442"
  public static let rolandNicePianoFileName = "RolandNicePiano"

  /// Obtain the name of the SF2 resource file without suffix
  public var fileName: String {
    switch self {
    case .fluidFont: return Self.fluidFontFileName
    case .freeFont: return Self.freeFontFileName
    case .museScore: return Self.museScoreFileName
    case .rolandNicePiano: return Self.rolandNicePianoFileName
    }
  }
}

extension SF2ResourceFileTag {

  public static let fluidFontName = "Fluid R3"
  public static let freeFontName = freeFontFileName
  public static let museScoreName = "MuseScore"
  public static let rolandNicePianoName = "Roland Piano"

  /// Obtain the name of the SF2 resource
  public var name: String {
    switch self {
    case .fluidFont: return Self.fluidFontName
    case .freeFont: return Self.freeFontName
    case .museScore: return Self.museScoreName
    case .rolandNicePiano: return Self.rolandNicePianoName
    }
  }
}

extension SF2ResourceFileTag {

  /// Obtain the `resources` index associated with the tag
  public var resourceIndex: Int { self.rawValue - 1 }

  /// Obtain the URL for an SF2 file in the bundle
  public var url: URL { SF2ResourceFiles.resources[resourceIndex] }
}

extension SF2ResourceFileTag {

  /// Obtain info and preset info about an SF2 file
  public var fileInfo: Engine.SF2FileInfo? {
    var fileInfo = Engine.SF2FileInfo(url.path(percentEncoded: false))
    return fileInfo.load() ? fileInfo : nil
  }
}
