// Copyright © 2025 Brad Howes. All rights reserved.

import FeatureSupport

/**
 Minor feature that represents section of presets where each section has N preset buttons in it.

 The app can build sections as collections of 20 presets, or as collections of presets ordered by the first
 character in the preset name. Which kind is determined by the `sortPresetsByName` config item. Sections are generated by the
 `group` method.

 Actions from buttons reach their enclosing container and are then remapped into delegate actions and forwarded on to the enclosing
 `PresetsList` instance.
 */
@Reducer
public struct PresetsListSection {

  @ObservableState
  public struct State: Equatable, Identifiable {
    public let id: Int // 0 is first section, 1 second, etc.
    public let title: String
    public let indexKey: String
    public var rows: IdentifiedArrayOf<PresetButton.State>

    /**
     Create new state for a section.

     - parameter id: the numeric ID for the section (0 is first, 1 second, etc.)
     - parameter title: the full title of the section, usually shown in a list header
     - parameter indexKey: the unique index key for the section. Shown on the side of the preset list for quick scrolling
     */
    public init(
      id: Int,
      title: String,
      indexKey: String,
      presets: ArraySlice<Preset>,
    ) {
      @Shared(.favoriteSymbolName) var symbolName
      @Shared(.starFavoriteNames) var starFavoriteNames
      let symbolPrefix = starFavoriteNames ? symbolName : nil

      self.id = id
      self.title = title
      self.indexKey = indexKey
      self.rows = .init(
        uniqueElements: presets.map {
          .init(
            id: $0.id,
            displayName: $0.displayName,
            kind: $0.kind,
            symbolPrefix: $0.isFavorite ? symbolPrefix : nil
          )
        }
      )
    }

    /**
     Update any row that is showing the given preset

     - parameter presetId: the preset to update
     - parameter displayName: the new display name to show
     */
    public mutating func update(presetId: Preset.ID, displayName: String) {
      guard let index = rows.firstIndex(where: { $0.id == presetId }) else { return }
      rows[index].displayName = displayName
    }
  }

  public enum Action: Equatable {
    case delegate(Delegate)
    case rows(IdentifiedActionOf<PresetButton>)

    @CasePathable
    public enum Delegate: Equatable {
      case createFavoriteTapped(Preset.ID)
      case deleteFavoriteTapped(Preset.ID)
      case editPresetTapped(Preset.ID)
      case headerTapped(section: PresetsListSection.State.ID, count: Int)
      case hidePresetTapped(Preset.ID)
      case searchButtonTapped
      case presetButtonTapped(Preset.ID)
    }
  }

  public init() {}

  public var body: some ReducerOf<Self> {
    Reduce<State, Action> { state, action in
      switch action {

      case let .rows(.element(id: _, action: .delegate(action))):
        return processRowAction(&state, action: action)

      default:
        return .none
      }
    }
    .forEach(\.rows, action: \.rows) {
      PresetButton()
    }
  }

  private func processRowAction(_ state: inout State, action: PresetButton.Action.Delegate) -> Effect<Action> {
    switch action {
    case let .createFavoriteTapped(presetId): return .send(.delegate(.createFavoriteTapped(presetId)))
    case let .deleteFavoriteTapped(presetId): return .send(.delegate(.deleteFavoriteTapped(presetId)))
    case let .editPresetTapped(presetId): return .send(.delegate(.editPresetTapped(presetId)))
    case let .hidePresetTapped(presetId): return .send(.delegate(.hidePresetTapped(presetId)))
    case let .presetButtonTapped(presetId): return .send(.delegate(.presetButtonTapped(presetId)))
    }
  }
}

public struct PresetsListSectionView: View {
  private var store: StoreOf<PresetsListSection>
  private let searching: Bool
  private let activePresetId: Preset.ID?
  private let presetSource: PresetSource?
  @State private var showSearchButton: Bool = false
  @Environment(\.editMode) private var editMode
  private var editingVisibility: Bool { (editMode?.wrappedValue ?? .inactive) == .active }

  public init(
    store: StoreOf<PresetsListSection>,
    searching: Bool,
    activePresetId: Preset.ID?,
    presetSource: PresetSource?
  ) {
    self.store = store
    self.searching = searching
    self.activePresetId = activePresetId
    self.presetSource = presetSource
  }

  public var body: some View {
    Section {
      ForEach(store.scope(\.rows, action: \.rows), id: \.state.id) { rowStore in
        StyledEntry {
          PresetButtonView(
            store: rowStore,
            indicatorModifierState: indicatorModifierState(for: rowStore.state)
          )
        }
      }
    } header: {
      StyledHeader {
        HStack {
          SectionIndexTitleView(title: store.title)
            .frame(maxWidth: .infinity, alignment: .leading)
            .contentShape(Rectangle())
          Spacer()
          Button {
            store.send(.delegate(.searchButtonTapped))
          } label: {
            HStack {
              Image(systemName: .searchButtonImageName)
                .imageScale(.small)
                .contentShape(Rectangle())
              // Here to keep from overlapping the section index overlay from the parent view
              Color.clear
                .frame(width: 16)
            }
          }
          .opacity((showSearchButton || store.id == 0) && !searching && !editingVisibility ? 1.0 : 0.0)
          .animation(.smooth(duration: 0.2), value: showSearchButton)
        }
        // Track vertical position of our header -- when it becomes pinned, show the search button
        .onGeometryChange(for: Double.self) {
          $0.frame(in: .global).origin.y
        } action: {
          // !!! Magic constant hack to signal if section header should have the search button. This works ok except on iPhone in
          // landscape mode. Better to rely on some signal that the previous section header is going away.
          showSearchButton = $0 < 74.0
        }
      }
      .onTapGesture(count: 2) {
        store.send(.delegate(.headerTapped(section: store.id, count: 2)))
      }
      .onTapGesture(count: 1) {
        store.send(.delegate(.headerTapped(section: store.id, count: 1)))
      }
    }
    .id(store.indexKey) // Use this value since it is what is used when scrolling via the index view
    .animation(.smooth, value: store.rows)
  }

  private func indicatorModifierState(for state: PresetButton.State) -> IndicatorModifier.State {
    if presetSource?.isActive ?? false,
       activePresetId == state.id {
      return state.kind == .favorite ? .activeFavorite : .active
    }
    return state.kind == .favorite ? .favorite : .none
  }
}

/// A preference key to store ScrollView offset
public struct ViewOffsetKey: PreferenceKey {
  public typealias Value = CGFloat
  public static let defaultValue = CGFloat.zero
  public static func reduce(value: inout Value, nextValue: () -> Value) {
    value += nextValue()
  }
}

#if DEBUG

#Preview {
  // swiftlint:disable:next redundant_discardable_let
  let _ = prepareDependencies {
    installApplicationFont()
    $0.defaultDatabase = previewDatabase()
  }
  PresetsListView.preview
}

#endif // DEBUG
