// Copyright © 2025 Brad Howes. All rights reserved.

import FeatureSupport
import Tagged

/**
 Minor feature that represents section of presets where each section has N preset buttons in it.

 The app can build sections as collections of 20 presets, or as collections of presets ordered by the first
 character in the preset name. Which kind is determined by the `sortPresetsByName` config item. Sections are generated by the
 `group` method.

 Actions from buttons reach their enclosing container and are then remapped into delegate actions and forwarded on to the enclosing
 `PresetsList` instance.
 */
@Reducer
public struct PresetsListSection {

  @ObservableState
  public struct State: Equatable, Identifiable {
    public typealias ID = Tagged<Self, Int>

    public let id: ID
    public let section: Int // 0 is first section, 1 second, etc.
    public let sectionText: String
    public let sectionIndex: String
    public var rows: IdentifiedArrayOf<PresetButton.State>

    public init(
      section: Int,
      sectionText: String,
      sectionIndex: String,
      presets: ArraySlice<Preset>,
    ) {
      @Shared(.favoriteSymbolName) var symbolName
      @Shared(.starFavoriteNames) var starFavoriteNames
      let symbolPrefix = starFavoriteNames ? symbolName : nil

      self.id = .init(rawValue: section)
      self.section = section
      self.sectionText = sectionText
      self.sectionIndex = sectionIndex
      self.rows = .init(
        uniqueElements: presets.map {
          .init(
            preset: $0,
            symbolPrefix: $0.isFavorite ? symbolPrefix : nil
          )
        }
      )
    }

    /**
     Update any row that is showing the given preset

     - parameter presetId: the preset to update
     - parameter displayName: the new display name to show
     */
    public mutating func update(presetId: Preset.ID, displayName: String) {
      guard let index = rows.firstIndex(where: { $0.id == presetId }) else { return }
      rows[index].preset.displayName = displayName
    }
  }

  public enum Action: Equatable {
    case delegate(Delegate)
    case rows(IdentifiedActionOf<PresetButton>)

    @CasePathable
    public enum Delegate: Equatable {
      case createFavoriteTapped(Preset)
      case deleteFavoriteTapped(Preset)
      case editPresetTapped(Preset)
      case headerTapped(section: PresetsListSection.State.ID, count: Int)
      case hidePresetTapped(Preset)
      case searchButtonTapped
      case presetButtonTapped(Preset)
    }
  }

  public init() {}

  public var body: some ReducerOf<Self> {
    Reduce<State, Action> { state, action in
      switch action {

      case let .rows(.element(id: _, action: .delegate(action))):
        return processRowAction(&state, action: action)

      default:
        return .none
      }
    }
    .forEach(\.rows, action: \.rows) {
      PresetButton()
    }
  }

  private func processRowAction(_ state: inout State, action: PresetButton.Action.Delegate) -> Effect<Action> {
    switch action {
    case let .createFavoriteTapped(preset): return .send(.delegate(.createFavoriteTapped(preset)))
    case let .deleteFavoriteTapped(preset): return .send(.delegate(.deleteFavoriteTapped(preset)))
    case let .editPresetTapped(preset): return .send(.delegate(.editPresetTapped(preset)))
    case let .hidePresetTapped(preset): return .send(.delegate(.hidePresetTapped(preset)))
    case let .presetButtonTapped(preset): return .send(.delegate(.presetButtonTapped(preset)))
    }
  }
}

public struct PresetsListSectionView: View {
  private var store: StoreOf<PresetsListSection>
  private let searching: Bool
  private let activePresetId: Preset.ID?
  private let presetSource: PresetSource?
  @State private var showSearchButton: Bool = false
  @Environment(\.editMode) private var editMode
  private var editingVisibility: Bool { (editMode?.wrappedValue ?? .inactive) == .active }

  public init(
    store: StoreOf<PresetsListSection>,
    searching: Bool,
    activePresetId: Preset.ID?,
    presetSource: PresetSource?
  ) {
    self.store = store
    self.searching = searching
    self.activePresetId = activePresetId
    self.presetSource = presetSource
  }

  public var body: some View {
    Section {
      ForEach(store.scope(state: \.rows, action: \.rows)) { rowStore in
        StyledEntry {
          PresetButtonView(
            store: rowStore,
            indicatorModifierState: indicatorModifierState(for: rowStore.preset)
          )
        }
      }
    } header: {
      StyledHeader {
        HStack {
          SectionIndexTitleView(title: store.sectionText)
            .frame(maxWidth: .infinity, alignment: .leading)
            .contentShape(Rectangle())
          Spacer()
          Button {
            store.send(.delegate(.searchButtonTapped))
          } label: {
            HStack {
              Image(systemName: .searchButtonImageName)
                .imageScale(.small)
                .contentShape(Rectangle())
              // Here to keep from overlapping the section index overlay from the parent view
              Color.clear
                .frame(width: 16)
            }
          }
          .opacity((showSearchButton || store.section == 0) && !searching && !editingVisibility ? 1.0 : 0.0)
          .animation(.smooth(duration: 0.2), value: showSearchButton)
        }
        // Track vertical position of our header -- when it becomes pinned, show the search button
        .onGeometryChange(for: Double.self) {
          $0.frame(in: .global).origin.y
        } action: {
          // !!! Magic constant hack to signal if section header should have the search button. This works ok except on iPhone in
          // landscape mode. Better to rely on some signal that the previous section header is going away.
          showSearchButton = $0 < 74.0
        }
      }
      .onTapGesture(count: 2) {
        store.send(.delegate(.headerTapped(section: store.id, count: 2)))
      }
      .onTapGesture(count: 1) {
        store.send(.delegate(.headerTapped(section: store.id, count: 1)))
      }
    }
    .id(store.sectionIndex)
    .animation(.smooth, value: store.rows)
  }

  private func indicatorModifierState(for preset: Preset) -> IndicatorModifier.State {
    if presetSource?.isActive ?? false,
       presetSource?.id == preset.soundFontId,
       activePresetId == preset.id {
      return preset.isFavorite ? .activeFavorite : .active
    }
    return preset.isFavorite ? .favorite : .none
  }
}

/// A preference key to store ScrollView offset
public struct ViewOffsetKey: PreferenceKey {
  public typealias Value = CGFloat
  public static let defaultValue = CGFloat.zero
  public static func reduce(value: inout Value, nextValue: () -> Value) {
    value += nextValue()
  }
}

#if DEBUG

#Preview {
  // swiftlint:disable:next redundant_discardable_let
  let _ = prepareDependencies {
    installApplicationFont()
    $0.defaultDatabase = previewDatabase()
  }
  PresetsListView.preview
}

#endif // DEBUG
